macros: Add tests to check for HashMap scoping
This test makes sure that students use `::std::collections::HashMap`
instead of just `std::collections::HashMap`. It is intended
to show that a user can override the intended type.

The receive this error if the wrong scoping is used:

```
---- test_type_override stdout ----
thread 'test_type_override' panicked at 'Don't allow users to override which HashMap is used', tests/macros.rs:82:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```